name: Deploy to EC2 Auto Scaling Group

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./... -v

      - name: Build Docker image
        run: docker build -t my-app .

      - name: Tag Docker image
        run: docker tag my-app:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/my-app:latest

      - name: Push Docker image to ECR
        run: docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/my-app:latest

      - name: Deploy to EC2 Auto Scaling Group
        run: |
          aws deploy create-deployment \
            --application-name MyApplication \
            --deployment-group-name MyDeploymentGroup \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --github-location repository=my-app/repository,commitId=$GITHUB_SHA
            